application: fatcatmap
version: 4-dev
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:


###### Asset Handlers

# Images (Static)
- url: /assets/img/static
  static_dir: assets/img/static

# Images (Dynamic)
- url: /assets/img/.*
  script: assets/img/retrieve.py

# Style (Static Only)
- url: /assets/style
  static_dir: assets/style
  mime_type: text/css

# Scripts (Static Only)
- url: /assets/js
  static_dir: assets/js
  mime_type: text/javascript

# Generic (Static)
- url: /assets/ext/static
  static_dir: assets/ext/static

# Generic (Dynamic)
- url: /assets/ext/.*
  script: assets/ext/static/retrieve.py
  
# Library/system mappings
- url: /_ah/datastore_admin.*
  script: $PYTHON_LIB/google/appengine/ext/datastore_admin/main.py
  login: admin

- url: /_ah/mapreduce.*
  script: $PYTHON_LIB/google/appengine/ext/mapreduce/main.py
  login: admin

- url: /_ah/pipeline(/.*)?
  script: lib/pipeline/handlers.py
  login: admin

- url: /_pc/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_pc/mapreduce(/.*)?
  script: lib/mapreduce/main.py
  login: admin

- url: /_pc/manage/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always



###### Static Handlers

# Root-level files
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

# Static directory
- url: /static
  static_dir: static

###### Send to Tipfy
- url: /.*
  script: main.py
  login: admin