application: fatcatmap
version: 8-dev
runtime: python
api_version: 1

#### ===== Files to Skip
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$

#### ===== Builtin SDK Includes
builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

### ===== Custom Admin Pages
admin_console:
  pages:
  - name: Appstats
    url: /_perfstats

handlers:

###### Asset Handlers

# Images (Static)
- url: /assets/img/static
  static_dir: assets/img/static

# Images (Dynamic)
- url: /assets/img/.*
  script: assets/img/retrieve.py

# Style (Static Only)
- url: /assets/style
  static_dir: assets/style
  mime_type: text/css

# Scripts (Static Only)
- url: /assets/js/static
  static_dir: assets/js/static
  mime_type: text/javascript

# Generic (Static)
- url: /assets/ext/static
  static_dir: assets/ext/static

# Generic (Dynamic)
- url: /assets/ext/.*
  script: assets/ext/static/retrieve.py
  
# Library/system mappings
- url: /_perfstats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /_ah/datastore_admin.*
  script: $PYTHON_LIB/google/appengine/ext/datastore_admin/main.py
  login: admin

- url: /_ah/mapreduce.*
  script: $PYTHON_LIB/google/appengine/ext/mapreduce/main.py
  login: admin

- url: /_ah/pipeline(/.*)?
  script: lib/pipeline/handlers.py
  login: admin

- url: /_ah/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_pc/console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always


###### Static Handlers

# Root-level files
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(.*)
  
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"
  
- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: static/\1
  upload: static/(.*\.crx)
  
- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/\1
  upload: static/(.*\.woff)

# Static directory
- url: /static
  static_dir: static

###### Providence/Clarity Mappings
- url: /_pc/manage/.*
  script: momentum/platform/gateway/manage.py
  login: admin

#- url: /_pc/
#

###### API Requests to the Gateway
- url: /_api/rpc.*
  script: services.py

###### Send to Tipfy
- url: /.*
  script: main.py
  login: admin