stopwords = ["a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst", "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the"]


finn = """

Washington (CNN) -- The domestic political stakes of America's military intervention in Libya grew Friday, with critics continuing to question the mission's organization, cost and consequences.
The Obama administration, meanwhile, worked to balance promises of a rapid U.S. transition to a supporting role with an apparent unwillingness among coalition partners to have NATO assume full control of the mission.
President Obama conducted a conference call and meeting with congressional leaders to provide an update on the conflict and attempt to address their concerns. Democrats appeared more satisfied than Republicans.
"The president gave a very clear, very strong presentation," said Senate Armed Services Committee Chairman Carl Levin, D-Michigan. "He clearly answered the questions about the mission and planned schedule for the handoff of the principal responsibility for population protection to NATO and Arab countries."
But Brendan Buck, a spokesman for House Speaker John Boehner, R-Ohio, said Republicans "appreciated the update" but still believe "much more needs to be done by the administration to provide clarity, particularly to the American people, on the military objective in Libya, America's role, and how it is consistent with U.S. policy goals. 
"According to a White House statement, 21 senators and House members met with Obama and his national security team in the White House Situation Room.
NATO is preparing to take charge of the no-fly zone and arms embargo by the end of this weekend. The U.S. military, however, is still taking the lead -- at least for now -- on airstrikes intended to protect civilians.
U.S. officials have also made clear that they want to see strongman Moammar Gadhafi removed from power, a goal beyond the scope of the U.N. mandate.
Earlier in the day, Buck said the plan to give NATO an enhanced role "doesn't answer the questions" posed in a letter Boehner sent to Obama on Wednesday.
Among other things, Boehner asked Obama which U.S. allies would take the lead in enforcing of the no-fly zone. The speaker also asked whether there would be "clear lines of authority and responsibility and a chain of command."
In addition, Boehner asked whether the U.S. military would take on a larger role if the coalition fell apart.
California GOP Rep. Buck McKeon, the House Armed Services Committee chairman, wrote in a Washington Post op-ed Friday that he remains "skeptical of a military-led humanitarian mission that appears to be open-ended, generous with American resources, and could at some point be placed under a knotted international chain of command."
McKeon argued that there is a "mismatch" between U.N.-mandated civilian protection and the U.S. push to remove Gadhafi that could lead to a stalemate.
A veteran Democratic senator also questioned the wisdom of the U.S.'s role.
"I have very serious concerns about what this intervention means for our country in the coming weeks," said Sen. Jay Rockefeller, D-West Virginia. "Our military, and our budget, are stretched thin fighting two wars already, and I want to avoid getting into another conflict with unknown costs and consequences."
"We need to avoid deep military involvement in a third foreign country -- particularly in a country whose politics and society are largely unknown to us," Rockefeller added.
So far, U.S. forces have taken on the bulk of the Libyan mission, according to figures provided by the Pentagon. Of a total of 175 Tomahawk missiles fired, 168 were from the United States and seven from Great Britain, the only two countries to possess them, while U.S. planes have flown almost two-thirds of the sorties and U.S. ships constitute more than two-thirds of the total involved.
The U.N. resolution authorizes the no-fly zone, enforcement of an arms ban, and other steps as necessary to protect Libyan civilians. The U.S.-led coalition has interpreted that to include airstrikes on Libyan ground forces threatening the rebel stronghold of Benghazi and other areas.
White House Press Secretary Jay Carney promised Thursday that U.S. military forces will be shifting to a "support and assist" role in the international coalition within a matter of days. The United States is engaged in a "time-limited, scope-limited" action, he said.
A senior administration official asserted Thursday that details on the extent of NATO's mission were still being worked out.
The official, who spoke to reporters on condition of not being identified by name, said NATO ambassadors actually made two decisions Thursday. One was to take over command of the no-fly zone, and the other was a political decision to take responsibility for enforcing the full U.N. Security Council resolution authorizing the military mission.
"That latter part, we are still completing the operational planning and expect to be completed by this weekend," the official said.
Thursday's agreement was reached in a conference call between U.S. Secretary of State Hillary Clinton and her counterparts from Britain, France and Turkey, according to the senior administration official and diplomatic officials who spoke on condition of not being identified by name.
NATO sources said a major sticking point involved the rules of engagement for coalition forces enforcing the U.N. resolution, with Turkey raising concerns over details.
When NATO Secretary General Anders Fogh Rasmussen finally emerged to announce an agreement, it was clear that questions over the rules of engagement remained unresolved.
Asked if the announcement revealed a split in NATO over the mission, Rasmussen said no. However, he also acknowledged that if unaltered, the agreement would mean the overall Libyan mission would have two parts, with NATO enforcing the no-fly zone and arms blockade, and the U.S.-led coalition that launched the mission handling other necessary civilian protection.
Rasmussen said non-NATO partners including Arab countries would participate.
Clinton said she will travel to London on Tuesday to attend an international meeting on Libya that will include NATO allies and Arab partners in the Libya mission.

"""